name: Auto-Merge Release PRs

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  pull_request_review:
    types: [dismissed]
  workflow_dispatch:
    inputs:
      time_elapsed:
        description: 'Time elapsed since PR creation (e.g. "24h", "1d").'
        required: true
        default: '1d'

permissions: {}

jobs:
  auto-merge-releases:
    name: Auto Merge Releases
    permissions:
      contents: write # Required to merge PRs
      pull-requests: write # Required to merge PRs
    uses: TimSchoenle/actions/.github/workflows/maintenance-timed-auto-pr-approve.yaml@c706b8eba6061011f0bd3a23098728e9d73e2de4 # workflows-maintenance-timed-auto-pr-approve-v1.2.5
    with:
      time_elapsed: ${{ inputs.time_elapsed || '7d' }}
      branch_pattern: 'release-please--branches--%'
      trusted_authors: '253958393,248313786' # actions-maintenance-bot, automatic-release-manager
    secrets:
      app_id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
      private_key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
