name: Manual Update Helm Chart

on:
  push:

jobs:
  manual-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Update Helm Chart
        uses: ./.github/actions/update-helm-chart
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
          new-tag: 'v1.12.2'
          image-digest: 'sha256:cfddbb27deb7642099200e279019ca2f1c40143f97833b742dbee97d82c28737'
